sudo: false
language: rust
rust:
- 1.13.0
- nightly
- beta
- stable
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  pip install python-dateutil --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- |
  cargo build &&
  cargo test &&
  travis-cargo --only stable doc
after_success:
- travis-cargo --only stable doc-upload
env:
  global:
    secure: EYQhZ/2rKCcbpftjvO5UKNDoSRtRhRNQW1Qh0vHcnUZtF6/+VLaBHlkZpv6x+fQL/y9ffE4v8ECgj+30SQNGBNgtYwdw5gZs2NwjINadd+i9iR6LeP4FjRBGoezC5t+ce+uOSPTv1Aag8Nqlq85YJsoQgGT8gxJv9pm7lmkYFvjCt4rdZQ1qTJRDd5+StnXkaFnKeYohal/L51ZFnNWrc8LUKIAYNgPs6TRidIc0ghXNJPOjL5x4HTXXXQV5aduhEBcdPQrcArbiycJF2/Ru/56pwrHaQvfWV/AShHhoZ3KXSkJNUwgxj5sKhW3rjqmAbe/7npZ6dhyUZuh5VXkWMdMKcYOsaP2zJ58cI9irMnv/Q1Hn3Ip1gM1+zBaAEznx46oNBtg4AAyB7N5Oa+M7lDCqcgQNFFJ+IpCps5Mz+jbfNNHWeDyV2F0r4+7eKvfTfoaBwqpWDcOLoRj9Rc4y7Eg5f2PL5BWklaadaFfKtFhQNmU7s0yMvZ1KqmZEyEulqb+T189wR0lps3VC+AdFBBduG4kmYAJeRbb7Srt0KwdN9qslYhLMg+9r/gSr/KDRm3ekav2AVYVIVkN2LOkfaHzHsLioq/ALbZWiGzIc/pQWyIZysiLgWqYd3Ye3WcQhqD6AuA1YeMAk4jVtIL7FRxIkbeXglf4KAXh8iH7K8uY=
